### ISSUE TITLE
Discover Dishes: Filter By Mensa & Date & Allergies, Categories

### ISSUE THREAD

**Issue by lgiesen** [erikzimmermann/mensa-today#114]

**Comment by lgiesen** [comment]
preselected by date, food preferences and additives

**Comment by martenjostmann** [comment]
@lgiesen it would be nice if you can optimize the front end stuff here. The functionality of filtering by mensa and date is implemented now but there are some issues with the positioning of the text fields. Because vue is not hot reloading on my side it is a mess to update this. The date field is a bit shifted to the top. Maybe you can fix this.
![grafik](https://user-images.githubusercontent.com/47032832/210435269-e606d21f-487d-4bb9-8436-e1db75321eb9.png)

**Comment by martenjostmann** [comment]
The preselection of food preferences will be implemented after #177

**Comment by lgiesen** [comment]
I'll be on it after the seminar (15th Jan)
